name: Deploy Checks

on:
  pull_request:
    branches: [ dev ]
jobs:
  deploy_preview:
    name: Deploy Checks
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Compose services
        run: docker-compose build
      - name: Start Docker Compose services
        run: docker-compose up -d
      - name: List running services
        run: docker-compose ps
#      - name: Ensure services remain healthy
#        run:
      - name: Shutdown Docker Compose services
        run: docker-compose down